name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a276df624ca018f381a879236a5d97d409a3a2322a0ec4f94a8dc03687e54a7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
