name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e21b40ab5bb1b086c2d0700af3173c579520dfc67420cb99c9dab473f9efa208"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
