name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "144f2f7a982c88bc6d3d1a4e08aea5d6368c56e5b0b6bf88bfc7c5d600524325"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
